name: Juejin Auto Check-in and Lottery

on:
  schedule:
    # 每天北京时间上午9点执行 (UTC时间是1点)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  checkin-and-lottery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check-in to Juejin
        id: checkin
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Cookie: ${{ secrets.JUEJIN_COOKIE }}" \
            -d '{"aid": "${{ secrets.JUEJIN_AID }}", "uuid": "${{ secrets.JUEJIN_UUID }}"}' \
            https://api.juejin.cn/growth_api/v1/check_in)

          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$response" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check sign-in result
        run: |
          echo "Check-in completed. Response code and message:"
          echo "${{ steps.checkin.outputs.response }}"

      - name: Check lottery status
        id: lottery_status
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET \
            -H "Content-Type: application/json" \
            -H "Cookie: ${{ secrets.JUEJIN_COOKIE }}" \
            "https://api.juejin.cn/growth_api/v1/lottery_config/get?aid=${{ secrets.JUEJIN_AID }}&uuid=${{ secrets.JUEJIN_UUID }}")

          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$response" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        outputs:
          response: ${{ steps.lottery_status.outputs.response }}

      - name: Parse lottery status
        id: parse_lottery
        run: |
          free_count=$(echo '${{ steps.lottery_status.outputs.response }}' | head -n -1 | grep -o '"free_count":[0-9]*' | cut -d':' -f2)
          if [ "$free_count" = "" ]; then
            free_count=0
          fi
          echo "Free lottery count: $free_count"
          echo "free_count=$free_count" >> $GITHUB_OUTPUT

      - name: Draw lottery if available
        if: steps.parse_lottery.outputs.free_count > 0
        id: lottery
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Cookie: ${{ secrets.JUEJIN_COOKIE }}" \
            -d '{}' \
            "https://api.juejin.cn/growth_api/v1/lottery/draw?aid=${{ secrets.JUEJIN_AID }}&uuid=${{ secrets.JUEJIN_UUID }}")

          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$response" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show lottery result
        if: steps.parse_lottery.outputs.free_count > 0
        run: |
          echo "Lottery completed. Response:"
          echo "${{ steps.lottery.outputs.response }}"